#!/usr/bin/env fish

if test (uname) = "Darwin"
  set -x COPY  pbcopy
  set -x PASTE pbpaste
else
  set -x COPY  "xclip -selection clipboard"
  set -x PASTE "xclip -selection clipboard -o"
end

$PASTE | python -m codehighlighter.main $argv | $COPY
